#!/usr/bin/env bash

### Helpers begin
check_deps() {
    for d in "${deps[@]}"; do
        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
    done; unset d
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

Install or uninstall irc script

Options:
    -d, --dir=INSTALL_DIR    Install to specified directory
    -h, --help               Display this help message
    --nocolor                Disable colorized output
    -u, --uninstall          Uninstall

EOF
    exit "$1"
}

declare -a args deps
unset help
action="install"
bin="irc"
color="true"
install_dir="$HOME/.local/bin"

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-d"|"--dir"*) install_dir="$(long_opt "$@")" || shift ;;
        "-h"|"--help") help="true" ;;
        "--nocolor") unset color ;;
        "-u"|"--uninstall") action="uninstall" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0
[[ $# -eq 0 ]] || usage 1

unset sudo
case "$action" in
    "install")
        info "Installing..."
        mkdir -p "$install_dir"
        [[ -w $install_dir ]] || sudo="sudo"
        $sudo install -m 755 $bin "$install_dir/$bin"
        $sudo sed -i -e "s#INSTALL_DIR#$(pwd)#g" "$install_dir/$bin"
        ;;
    "uninstall")
        if [[ -f $install_dir/$bin ]]; then
            info "Uninstalling..."
            [[ -w $install_dir ]] || sudo="sudo"
            $sudo rm -f "$install_dir/$bin"
        else
            errx 2 "$bin is not installed in $install_dir"
        fi
        ;;
    *) usage 3 ;;
esac
good "Success"
info "Done"
